userList.directive('userList',function()
{
    return{
        scope:
        {
            active:'=',
            code:'='
        },
        controller:'userListController',
        templateUrl:'js/components/userList/template.html'
    };
});
